# Generated by Django 3.2.23 on 2024-01-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author_img',
            new_name='img',
        ),
    ]
