# Generated by Django 3.2.23 on 2024-01-05 20:41

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_author_img_quote_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
