# Generated by Django 3.2.23 on 2024-01-05 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240105_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
