# Generated by Django 3.2.23 on 2024-01-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240105_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
