# Generated by Django 3.2.23 on 2024-01-05 22:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240105_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='synopsis',
            field=ckeditor.fields.RichTextField(default='', max_length=1000),
        ),
    ]
